[[welcome-index]]
= Ansible Workshops
{product-author}
{product-version}
:data-uri:
:icons:
:qsguide: https://www.ansible.com/get-started
:videos: https://www.ansible.com/videos
:wandt: https://www.ansible.com/webinars-training
:docs: http://docs.ansible.com/
:blog: https://www.ansible.com/blog
:depth: https://www.ansible.com/ansible-in-depth-whitepaper
:examples: https://github.com/ansible/ansible-examples
:free_trial: https://www.ansible.com/tower-trial
:install: http://docs.ansible.com/ansible/intro_installation.html


---

[.lead]
Welcome to the Ansible Workshops repository, where you can
find information and guides to help you learn about Ansible!

[NOTE]
====
[.lead]
- Ansible is a radically simple IT automation engine that automates cloud provisioning, configuration management, application deployment, intra-service orchestration, and many other IT needs.

[.lead]
- Designed for multi-tier deployments since day one, Ansible models your IT infrastructure by describing how all of your systems inter-relate, rather than just managing one system at a time.

[.lead]
- It uses no agents and no additional custom security infrastructure, so it's easy to deploy - and most importantly, it uses a very simple language (YAML, in the form of Ansible Playbooks) that allow you to describe your automation jobs in a way that approaches plain English.
====

[.lead]
Please browse to the appropriate ansible workshop on the left to get started.

[.lead]
Happy learning!
